### ISSUE TITLE
Reduce wait period from 30s to maybe 10s

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/circleci-helper#9]
https://github.com/influxdata/circleci-helper/blob/b09750270138212ebe6830fecbe3c139a5878419/cmd/circleci-helper/internal/waitForJobs.go#L94-L96

One of our bottleneck pipelines block on this call -- in the worst case we have to wait 30 seconds longer after the upstream jobs complete.

Dropping the wait period down to 10s would be an easy change to help the bottleneck complete faster, or we could allow it to be configurable.

I saw that the [v1 API docs mention rate limiting](https://circleci.com/docs/api/#rate-limiting):

> For HTTP APIs, when a request is throttled, you will receive HTTP status code 429. If your integration requires that a throttled request is completed, then you should retry these requests after a delay, using an exponential backoff. In most cases, the HTTP 429 response code will be accompanied by the Retry-After HTTP header. When this header is present, your integration should wait for the period of time specified by the header value before retrying a request.

I am not seeing any docs on v2 API rate limiting.

**Comment by wojciechka** [comment]
Good idea. I'll make this configurable so it's easier to control in specific pipelines.
